apiVersion: v1
kind: ReplicationController
metadata:
  name: apache 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: apache 
    spec:
      containers:
      - name: apache 
        image: httpd:2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        